# Generated by Django 4.2.16 on 2024-11-20 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_vendor', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Produk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_produk', models.CharField(max_length=50)),
                ('nama_produk', models.CharField(max_length=255)),
                ('unit', models.CharField(max_length=10, null=True)),
                ('pack_size', models.IntegerField(null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('relasi_vendor', models.ManyToManyField(blank=True, to='ToolingApp.vendor')),
            ],
        ),
    ]
